version: "3.7"

services:
  ml-engine-api:
    container_name: ml-engine-api
    build:
        context: ./
    depends_on:
      - database
    ports:
      - 5000:5000
      
  database:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_volume:/var/lib/postgresql

volumes: 
  db_volume: