version: "3.7"

services:
  ml-api:
    build: .
    depends_on:
      - ml-db
    env_file: .env
    restart: always
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
      
  ml-db:
    image: postgres:latest
    env_file: .env
    restart: always
    networks: 
      - default
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
